# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’
use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod 'SwiftyJSON'
pod 'PromiseKit'
pod 'ReSwift', '2.1.0'

target 'MubalooSam' do
end

target 'MubalooSamTests' do
end

target 'MubalooSamUITests' do
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = 3.0
        end
    end
end
